name: Build and Release LaTeX Document

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout CV Repository
      uses: actions/checkout@v4
      with:
        repository: ${{ github.repository }}

    - name: Checkout Website Repository
      uses: actions/checkout@v4
      with:
        repository: ${{ secrets.WEBSITE_REPOSITORY }}
        path: website
        token: ${{ secrets.PAT_TOKEN }}

    - name: Compile French document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main_fr.tex
        working_directory: src

    - name: Compile English document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main_en.tex
        working_directory: src

    - name: Copy CV PDF to Website
      run: cp ./src/main*.pdf website/public/

    - name: Commit and Push Website
      run: |
        cd website
        git config --global user.name 'CV Actions Bot'
        git config --global user.email ''
        git add public/main_fr.pdf
        git add public/main_en.pdf
        git commit -m "Update CV"
        git push

    - name: Get Current Date
      run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Release
      uses: softprops/action-gh-release@v1
      if: github.ref == 'refs/heads/main'
      with:
        files: ./src/main*.pdf
        tag_name: ${{ env.CURRENT_DATE }}
        name: Release ${{ env.CURRENT_DATE }}
        body: "PDF document released on ${{ env.CURRENT_DATE }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}