name: Build and Release LaTeX Document

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Compile LaTeX document
      uses: xu-cheng/latex-action@v2
      with:
        root_file: main.tex
        working_directory: src

    - name: Get Current Date
      run: echo "CURRENT_DATE=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

    - name: Release
      uses: softprops/action-gh-release@v1
      if: github.ref == 'refs/heads/main'
      with:
        files: ./src/main.pdf
        tag_name: ${{ env.CURRENT_DATE }}
        name: Release ${{ env.CURRENT_DATE }}
        body: "PDF document released on ${{ env.CURRENT_DATE }}"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}